package archstate

import (
	"bufio"
	"bytes"
	"fmt"
	"os"
	"sort"
	"strings"
)

const generatedHeader = `# Auto-generated by archstate.
# Treat this file as read-only state. Use archstate commands to update it.
# Manual edits may be overwritten.

`

type entryValidator func(key, value string) error

func formatState(entries map[string]string) []byte {
	var buf bytes.Buffer
	buf.WriteString(generatedHeader)
	keys := make([]string, 0, len(entries))
	for key := range entries {
		keys = append(keys, key)
	}
	sort.Strings(keys)
	for _, key := range keys {
		fmt.Fprintf(&buf, "%s=%s\n", key, entries[key])
	}
	return buf.Bytes()
}

func writeStateFile(path string, entries map[string]string) error {
	return atomicWriteFile(path, formatState(entries), 0o644)
}

func readPackageStateForSync(path string) map[string]string {
	entries := make(map[string]string)
	file, err := os.Open(path)
	if err != nil {
		return entries
	}
	defer file.Close()

	scanner := bufio.NewScanner(file)
	for scanner.Scan() {
		line := scanner.Text()
		trimmed := strings.TrimSpace(line)
		if trimmed == "" || strings.HasPrefix(trimmed, "#") {
			continue
		}
		key, value, ok := splitEntryLine(line)
		if !ok {
			continue
		}
		if err := validatePackageEntry(key, value); err != nil {
			continue
		}
		entries[key] = value
	}
	return entries
}

func readStateFileStrict(path string, validate entryValidator) (map[string]string, error) {
	file, err := os.Open(path)
	if err != nil {
		return nil, err
	}
	defer file.Close()

	entries := make(map[string]string)
	scanner := bufio.NewScanner(file)
	lineNo := 0
	for scanner.Scan() {
		lineNo++
		line := scanner.Text()
		trimmed := strings.TrimSpace(line)
		if trimmed == "" {
			continue
		}
		if strings.HasPrefix(trimmed, "#") {
			if isGeneratedHeaderLine(trimmed) {
				continue
			}
			return nil, fmt.Errorf("%s:%d: unsupported comment", path, lineNo)
		}
		key, value, ok := splitEntryLine(line)
		if !ok {
			return nil, fmt.Errorf("%s:%d: expected key=value", path, lineNo)
		}
		if _, exists := entries[key]; exists {
			return nil, fmt.Errorf("%s:%d: duplicate key %q", path, lineNo, key)
		}
		if err := validate(key, value); err != nil {
			return nil, fmt.Errorf("%s:%d: %w", path, lineNo, err)
		}
		entries[key] = value
	}
	if err := scanner.Err(); err != nil {
		return nil, err
	}
	return entries, nil
}

func readStateFileStrictOptional(path string, validate entryValidator) (map[string]string, error) {
	entries, err := readStateFileStrict(path, validate)
	if err != nil && os.IsNotExist(err) {
		return map[string]string{}, nil
	}
	return entries, err
}

func splitEntryLine(line string) (string, string, bool) {
	key, value, ok := strings.Cut(line, "=")
	if !ok {
		return "", "", false
	}
	if key != strings.TrimSpace(key) || value != strings.TrimSpace(value) {
		return "", "", false
	}
	return key, value, true
}

func isGeneratedHeaderLine(line string) bool {
	switch line {
	case "# Auto-generated by archstate.",
		"# Treat this file as read-only state. Use archstate commands to update it.",
		"# Manual edits may be overwritten.":
		return true
	default:
		return false
	}
}

func validatePackageEntry(key, value string) error {
	if err := validateDirectChildName(key); err != nil {
		return fmt.Errorf("invalid package name %q: %w", key, err)
	}
	if strings.ContainsRune(value, 0) {
		return fmt.Errorf("description contains NUL")
	}
	return nil
}

func validateManagedEntry(key, value string) error {
	if err := validateDirectChildName(key); err != nil {
		return fmt.Errorf("invalid config name %q: %w", key, err)
	}
	if err := validateDirectChildName(value); err != nil {
		return fmt.Errorf("invalid repo target %q: %w", value, err)
	}
	return nil
}

func validateDirectChildName(name string) error {
	if name == "" {
		return fmt.Errorf("empty name")
	}
	if name != strings.TrimSpace(name) {
		return fmt.Errorf("leading or trailing whitespace")
	}
	if name == "." || name == ".." {
		return fmt.Errorf("reserved path segment")
	}
	if strings.ContainsAny(name, `/\`) {
		return fmt.Errorf("must be a direct child name")
	}
	if strings.ContainsRune(name, 0) {
		return fmt.Errorf("contains NUL")
	}
	return nil
}
