package archstate

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestServiceInstallWritesUserUnits(t *testing.T) {
	env := newTestEnv(t)
	env.initRepo(t)
	configureServiceTestBinary(t, env)
	log := writeFakeSystemctl(t, env, `
printf '%s\n' "$*" >> "$ARCHSTATE_SYSTEMCTL_LOG"
`)

	if err := env.run("service", "install"); err != nil {
		t.Fatal(err)
	}

	servicePath := filepath.Join(env.home, ".config", "systemd", "user", serviceUnitName)
	timerPath := filepath.Join(env.home, ".config", "systemd", "user", timerUnitName)
	service := readFile(t, servicePath)
	for _, want := range []string{
		"# Auto-generated by archstate.",
		"ConditionPathExists=" + filepath.Join(env.repo, markerFile),
		"ExecStart=%h/.local/bin/archstate sync --commit",
		"WorkingDirectory=" + env.repo,
		"Nice=10",
		"IOSchedulingClass=idle",
	} {
		if !strings.Contains(service, want) {
			t.Fatalf("service unit missing %q:\n%s", want, service)
		}
	}

	timer := readFile(t, timerPath)
	for _, want := range []string{
		"OnBootSec=5min",
		"OnUnitActiveSec=1h",
		"RandomizedDelaySec=10min",
		"Persistent=true",
		"Unit=archstate-sync.service",
	} {
		if !strings.Contains(timer, want) {
			t.Fatalf("timer unit missing %q:\n%s", want, timer)
		}
	}

	if got := readFile(t, log); !strings.Contains(got, "--user daemon-reload") {
		t.Fatalf("service install did not reload systemd user manager:\n%s", got)
	}
	for _, want := range []string{
		"installed archstate sync service files",
		"enable with: archstate service enable",
	} {
		if !strings.Contains(env.stdout.String(), want) {
			t.Fatalf("service install output missing %q:\n%s", want, env.stdout.String())
		}
	}
}

func TestServiceEnableStatusDisableAndUninstall(t *testing.T) {
	env := newTestEnv(t)
	env.initRepo(t)
	configureServiceTestBinary(t, env)
	log := writeFakeSystemctl(t, env, `
printf '%s\n' "$*" >> "$ARCHSTATE_SYSTEMCTL_LOG"
case "$*" in
  "--user show archstate-sync.timer --property=UnitFileState --value")
    printf 'enabled\n'
    ;;
  "--user show archstate-sync.timer --property=ActiveState --value")
    printf 'active\n'
    ;;
esac
`)

	if err := env.run("service", "install"); err != nil {
		t.Fatal(err)
	}
	if err := env.run("service", "enable"); err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(env.stdout.String(), "enabled archstate sync timer") {
		t.Fatalf("unexpected enable output:\n%s", env.stdout.String())
	}

	if err := env.run("service", "status"); err != nil {
		t.Fatal(err)
	}
	for _, want := range []string{
		"service file: ~/.config/systemd/user/archstate-sync.service (installed)",
		"timer file:   ~/.config/systemd/user/archstate-sync.timer (installed)",
		"enabled:      enabled",
		"active:       active",
	} {
		if !strings.Contains(env.stdout.String(), want) {
			t.Fatalf("service status missing %q:\n%s", want, env.stdout.String())
		}
	}

	if err := env.run("service", "disable"); err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(env.stdout.String(), "disabled archstate sync timer") {
		t.Fatalf("unexpected disable output:\n%s", env.stdout.String())
	}

	if err := env.run("service", "uninstall"); err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(env.stdout.String(), "removed archstate sync service files") {
		t.Fatalf("unexpected uninstall output:\n%s", env.stdout.String())
	}
	for _, path := range []string{
		filepath.Join(env.home, ".config", "systemd", "user", serviceUnitName),
		filepath.Join(env.home, ".config", "systemd", "user", timerUnitName),
	} {
		if _, err := os.Lstat(path); !os.IsNotExist(err) {
			t.Fatalf("expected %s to be removed: %v", path, err)
		}
	}

	calls := readFile(t, log)
	for _, want := range []string{
		"--user enable --now archstate-sync.timer",
		"--user disable --now archstate-sync.timer",
		"--user show archstate-sync.timer --property=UnitFileState --value",
		"--user show archstate-sync.timer --property=ActiveState --value",
	} {
		if !strings.Contains(calls, want) {
			t.Fatalf("systemctl calls missing %q:\n%s", want, calls)
		}
	}
}

func configureServiceTestBinary(t *testing.T, env *testEnv) {
	t.Helper()
	source := filepath.Join(env.bin, "archstate-source")
	writeExecutable(t, source, "true\n")
	env.r.ExecutablePath = source
}

func writeFakeSystemctl(t *testing.T, env *testEnv, body string) string {
	t.Helper()
	log := filepath.Join(env.root, "systemctl.log")
	env.r.Env = append(env.r.Env, "ARCHSTATE_SYSTEMCTL_LOG="+log)
	writeExecutable(t, filepath.Join(env.bin, "systemctl"), body)
	return log
}
