package archstate

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

const (
	serviceUnitName = "archstate-sync.service"
	timerUnitName   = "archstate-sync.timer"
)

type serviceUnitPaths struct {
	dir     string
	service string
	timer   string
}

func (r *Runner) runService(args []string) error {
	if len(args) == 1 && isHelpArg(args[0]) {
		return r.printCommandHelp("service")
	}
	if len(args) != 1 {
		return fmt.Errorf("usage: archstate service install|enable|status|disable|uninstall")
	}
	switch args[0] {
	case "install":
		return r.runServiceInstall()
	case "enable":
		return r.runServiceEnable()
	case "status":
		return r.runServiceStatus()
	case "disable":
		return r.runServiceDisable()
	case "uninstall":
		return r.runServiceUninstall()
	default:
		return fmt.Errorf("unknown service command %q", args[0])
	}
}

func (r *Runner) runServiceInstall() error {
	repo, err := r.discoverExistingRepo()
	if err != nil {
		return err
	}
	if err := r.runInstall(false); err != nil {
		return err
	}

	paths := r.serviceUnitPaths()
	if err := os.MkdirAll(paths.dir, 0o755); err != nil {
		return err
	}
	if err := atomicWriteFile(paths.service, []byte(serviceUnit(repo)), 0o644); err != nil {
		return err
	}
	if err := atomicWriteFile(paths.timer, []byte(timerUnit()), 0o644); err != nil {
		return err
	}
	if err := r.systemctlUser("daemon-reload"); err != nil {
		return err
	}

	fmt.Fprintln(r.Stdout, "installed archstate sync service files")
	fmt.Fprintf(r.Stdout, "  service: %s\n", homeRelativePath(r.Home, paths.service))
	fmt.Fprintf(r.Stdout, "  timer:   %s\n", homeRelativePath(r.Home, paths.timer))
	fmt.Fprintln(r.Stdout, "enable with: archstate service enable")
	return nil
}

func (r *Runner) runServiceEnable() error {
	paths := r.serviceUnitPaths()
	if !pathExists(paths.service) || !pathExists(paths.timer) {
		return fmt.Errorf("service is not installed; run archstate service install")
	}
	if err := r.systemctlUser("daemon-reload"); err != nil {
		return err
	}
	if err := r.systemctlUser("enable", "--now", timerUnitName); err != nil {
		return err
	}
	fmt.Fprintln(r.Stdout, "enabled archstate sync timer")
	return nil
}

func (r *Runner) runServiceStatus() error {
	paths := r.serviceUnitPaths()
	fmt.Fprintln(r.Stdout, "Archstate sync service:")
	fmt.Fprintf(r.Stdout, "  service file: %s (%s)\n", homeRelativePath(r.Home, paths.service), installedState(paths.service))
	fmt.Fprintf(r.Stdout, "  timer file:   %s (%s)\n", homeRelativePath(r.Home, paths.timer), installedState(paths.timer))
	fmt.Fprintf(r.Stdout, "  enabled:      %s\n", r.systemctlUserProperty(timerUnitName, "UnitFileState"))
	fmt.Fprintf(r.Stdout, "  active:       %s\n", r.systemctlUserProperty(timerUnitName, "ActiveState"))
	if !pathExists(paths.service) || !pathExists(paths.timer) {
		fmt.Fprintln(r.Stdout, "install: archstate service install")
		return nil
	}
	fmt.Fprintln(r.Stdout, "inspect: systemctl --user list-timers archstate-sync.timer")
	return nil
}

func (r *Runner) runServiceDisable() error {
	if err := r.systemctlUser("disable", "--now", timerUnitName); err != nil {
		return err
	}
	fmt.Fprintln(r.Stdout, "disabled archstate sync timer")
	return nil
}

func (r *Runner) runServiceUninstall() error {
	_ = r.systemctlUser("disable", "--now", timerUnitName)

	paths := r.serviceUnitPaths()
	if err := removeIfExists(paths.service); err != nil {
		return err
	}
	if err := removeIfExists(paths.timer); err != nil {
		return err
	}
	if err := r.systemctlUser("daemon-reload"); err != nil {
		return err
	}
	fmt.Fprintln(r.Stdout, "removed archstate sync service files")
	return nil
}

func (r *Runner) serviceUnitPaths() serviceUnitPaths {
	dir := filepath.Join(r.Home, ".config", "systemd", "user")
	return serviceUnitPaths{
		dir:     dir,
		service: filepath.Join(dir, serviceUnitName),
		timer:   filepath.Join(dir, timerUnitName),
	}
}

func serviceUnit(repo repoPaths) string {
	repoPath := systemdUnitPath(repo.path)
	markerPath := systemdUnitPath(repo.markerPath())
	return fmt.Sprintf(`# Auto-generated by archstate.
# Use archstate service install/uninstall to manage this file.

[Unit]
Description=Sync Archstate package state
ConditionPathExists=%s

[Service]
Type=oneshot
ExecStart=%%h/.local/bin/archstate sync --commit
WorkingDirectory=%s
Nice=10
IOSchedulingClass=idle
`, markerPath, repoPath)
}

func timerUnit() string {
	return `# Auto-generated by archstate.
# Use archstate service install/uninstall to manage this file.

[Unit]
Description=Run Archstate package sync periodically

[Timer]
OnBootSec=5min
OnUnitActiveSec=1h
RandomizedDelaySec=10min
Persistent=true
Unit=archstate-sync.service

[Install]
WantedBy=timers.target
`
}

func systemdUnitPath(path string) string {
	path = strings.ReplaceAll(path, "%", "%%")
	if !strings.ContainsAny(path, " \t\n\"\\") {
		return path
	}
	path = strings.ReplaceAll(path, `\`, `\\`)
	path = strings.ReplaceAll(path, `"`, `\"`)
	return `"` + path + `"`
}

func installedState(path string) string {
	if pathExists(path) {
		return "installed"
	}
	return "missing"
}

func removeIfExists(path string) error {
	if err := os.Remove(path); err != nil && !os.IsNotExist(err) {
		return err
	}
	return nil
}

func (r *Runner) systemctlUser(args ...string) error {
	return r.streamCommand("systemctl", append([]string{"--user"}, args...)...)
}

func (r *Runner) systemctlUserProperty(unit, property string) string {
	out, err := r.commandOutput("systemctl", "--user", "show", unit, "--property="+property, "--value")
	if err != nil {
		return "unknown"
	}
	value := strings.TrimSpace(out)
	if value == "" {
		return "unknown"
	}
	return value
}
